### ISSUE TITLE
Lottie.Sample UWP ?

### ISSUE THREAD

**Issue by abrasat** [jfversluis/LottieSample#1]
Could you please add also the UWP support to the LottieSample ?

**Comment by jfversluis** [comment]
It shouldn't be very different from the other ones. Are you running into problems?

**Comment by abrasat** [comment]
Yes, when using a NetStandard "common" project for Xamarin.Forms (posted [here](https://github.com/martijn00/LottieXamarin/issues/122#issuecomment-356306859) )

**Comment by azchohfi** [comment]
I'll fix it! https://github.com/azchohfi/LottieUWP/issues/6

**Comment by jfversluis** [comment]
Great @azchohfi, thank you! 
With that, I'll close the issue here.

**Comment by jfversluis** [comment]
@abrasat a UWP version is added to the repo thanks to @azchohfi
