### ISSUE TITLE
LottieSample.iOS compilation: "framework not found FileProvider for architecture x86_64"

### ISSUE THREAD

**Issue by abrasat** [jfversluis/LottieSample#2]
I am using the iPhoneSimulator with an "older" MacBook on which can be installed only XCode 8.2.1, and the LottieSample.iOS application generation (with the LinkerBehavior is set to "Link Framework SDKs only") fails with the message

error : Native linking error: framework not found FileProvider for architecture x86_64

**Comment by jfversluis** [comment]
Although I'd be happy to help, this project is meant to provide sample code and not a full-featured app. Therefore I cannot help you with this issue, I'm sorry.

Please try to setup your own project with this library, if the problem keeps occuring, please raise an issue on the project's Github.
